controllers:
  resource: '../src/Controller/'
  type: 'attribute'

file_upload:
    path: /upload
    controller: 'App\Controller\FileUploadController::upload'
    methods: ['GET', 'POST']

api_login_check:
    path: /api/login_check
